image: node:16.20.1-alpine3.17
stages:
  - build
  - deploy




pages:
  image: node:16.20.1-alpine3.17
  stage: build
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

######################################### Deploy #########################################
deploy-dev:
  stage: deploy
  before_script:
    - npm install -g firebase-tools@11.13.0
  script:
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
  only:
    refs:
      - main
  environment:
    name: main