image: node:16.20.1-alpine3.17
stages:
  - build
  - deploy

build-dev:
  image: node:16.20.1-alpine3.17
  stage: build
  only:
    - main
  before_script:
    - rm -rf node_modules
    - npm i -g npm
  script:
    - npm i
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
    expire_in: 1 week
  environment:
    name: main

######################################### Deploy #########################################
deploy-dev:
  stage: deploy
  before_script:
    - npm install -g firebase-tools@11.13.0
  script:
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
  only:
    refs:
      - main
  environment:
    name: main